// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0i6qLocxkf84yPTqrhQ0jeF2lJLrXDbE',
    appId: '1:808580011359:web:d822363a98f1412a53d2ea',
    messagingSenderId: '808580011359',
    projectId: 'reddit-clone-new',
    authDomain: 'reddit-clone-new-eeadb.firebaseapp.com',
    storageBucket: 'reddit-clone-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3HxJDVEngzwbGkeIbqp7OchQlAA7GpU',
    appId: '1:808580011359:android:1a7a8d6f74425c9553d2ea',
    messagingSenderId: '808580011359',
    projectId: 'reddit-clone-new',
    storageBucket: 'reddit-clone-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8016YtCiksZLmgOSMBdX8p0KxYPNPoGo',
    appId: '1:808580011359:ios:45c26d4d46e9c72e53d2ea',
    messagingSenderId: '808580011359',
    projectId: 'reddit-clone-new',
    storageBucket: 'reddit-clone-new.appspot.com',
    iosClientId: '808580011359-424f0028qppvkugnl7g2lngj7d1gvlpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8016YtCiksZLmgOSMBdX8p0KxYPNPoGo',
    appId: '1:808580011359:ios:45c26d4d46e9c72e53d2ea',
    messagingSenderId: '808580011359',
    projectId: 'reddit-clone-new',
    storageBucket: 'reddit-clone-new.appspot.com',
    iosClientId: '808580011359-424f0028qppvkugnl7g2lngj7d1gvlpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
